import {
    IdentificationCard,
    ChatsCircle,
    UserCircle,
    EnvelopeSimple,
    Phone,
    Robot,
    Timer,
    IconProps,
    List,
    SquaresFour,
    PuzzlePiece,
    Users,
    Gear,
    SignOut,
    SignIn,
    CaretLeft,
    WarningCircle,
    FacebookLogo,
    WhatsappLogo,
    InstagramLogo,
    SlackLogo,
    ClockCounterClockwise,
    Folder,
    CaretRight,
    Calendar,
    Bell,
    Info,
    CaretCircleRight,
    MagnifyingGlass,
    Link,
    File,
    UserPlus,
    Eye,
    EyeSlash,
    Moon,
    Sun,
    ShoppingCart,
    User,
} from "phosphor-react";

interface CoreIconType {
    [key: string]: React.FC<IconProps>;
}

const CoreIcon: CoreIconType = {
    IdentificationCard,
    ChatsCircle,
    UserCircle,
    EnvelopeSimple,
    Phone,
    Robot,
    Timer,
    List,
    SquaresFour,
    PuzzlePiece,
    Users,
    Gear,
    SignOut,
    SignIn,
    CaretLeft,
    WarningCircle,
    FacebookLogo,
    WhatsappLogo,
    InstagramLogo,
    SlackLogo,
    ClockCounterClockwise,
    Folder,
    CaretRight,
    Calendar,
    Bell,
    Info,
    CaretCircleRight,
    MagnifyingGlass,
    Link,
    File,
    UserPlus,
    Eye,
    EyeSlash,
    Moon,
    Sun,
    ShoppingCart,
    User,
};

export default CoreIcon;
